version: '3'

services:
  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    ports:
      - 8000:3000
    container_name: api-gateway-container

  url:
    build:
      context: .
      dockerfile: ./apps/url/Dockerfile
    ports:
      - 5000:5000
    container_name: url-container
